# Generated by Django 5.0 on 2024-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Completed')], default='In Progress'),
        ),
    ]
