# Generated by Django 5.0 on 2024-01-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_tag_remove_note_tags_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress'),
        ),
    ]
